### ISSUE TITLE
Getting started with Guan?

### ISSUE THREAD

**Issue by d-vyd** [microsoft/Guan#14]
Hi! Is Guan an ongoing project? I'm fairly new to c# and Visual Studio but would really like to experiment with it. I don't see the package available via Nuget. Could you explain the steps necessary to include Guan in a simple application? From the p1.test file, it looks like an application might submit facts to the Guan subsystem via the keyword "rules" and ask questions via the keyword "query" with content in Prolog syntax as a string?

**Comment by GitTorre** [comment]
Hi,

Yes, Guan is an ongoing project, developed in the open, and currently in Preview. It will become 1.0 soon. 

You can see a working example of consuming Guan and using Guan's API here: https://github.com/microsoft/service-fabric-healer This project also explains, in detail, how it employs Guan (see the related documentation files).

Guan, like Prolog, processes logic rules, which are typically housed in text files (but can be string variables, as well, in the consuming program). 

Guan is available in the public nuget.org gallery: https://www.nuget.org/packages/Microsoft.Logic.Guan/1.0.1-Preview

**Comment by d-vyd** [comment]
Thank you so much for this detailed response. I'll look at the resources you linked to.

**Comment by d-vyd** [comment]
Hi Charles,

I combed through the FabricHealer solution and found RepairTaskManager.cs which uses Guan. The code is beyond my programming abilities but is well commented, so I'll try to figure it out. I see that the Prolog terms are stored in text files in the LogicRules directory. 

As an alternative, I have CSProlog working because of the short example at https://github.com/jsakamoto/CSharpProlog and discussion in the related forum. It actually runs on my phone via Xamarin.Forms. In the long run, I'd like to switch to a more current Prolog implementation like Guan.

-david

**Comment by GitTorre** [comment]
The key things to look at in FabricHealer (which is a narrow, domain-specific implementation with respect to Guan) are the logic rules themselves, the external predicate implementations (see the Repair\Guan folder), and also how the facts (data from a different service, FabricObserver) are presented to Guan for use in related logic rules, how the external predicates are initialized and made available to the Guan query engine, and how to execute a query. The function ```RunGuanQueryAsync``` in RepairTaskManager.cs is where you should begin. For sure there is a lot going on in FabricHealer that is unrelated to Guan, but the code is organized in such a way that it should be relatively easy to focus on how Guan is employed without also understanding the unrelated code. 

Basically, in FabricHealer, logic (with Guan) forms the basis of repair (auto-mitigation) workflow definition/configuration. Let's look at a simple logic rule that would be in AppRules.config.txt (the repair target in this case is a Service Fabric application):  

```Prolog
Mitigate(AppName="fabric:/PortEater42", MetricName="EphemeralPorts", MetricValue=?MetricValue) :- ?MetricValue >= 8500,
	TimeScopedRestartCodePackage(4, 01:00:00).
```

The rule above is composed of a head (or goal), Mitigate, which is full of facts (or data from FabricObserver related to the application-level issue that was detected). As you can see in ```RunGuanQueryAsync```, this information is stored in a ```CompoundTerm``` object named "Mitigate" (which, of course, is also the name of the goal or head in all rules) as named Arguments with corresponding values (of varying types). These arguments are then used in the sub rules (or sub goals) and form the basis of the logical workflow. You can interpret the rule to mean: If an application named "fabric:/PortEater42" is consuming 8500 or more ports in the dynamic range (aka ephemeral ports) then restart the application's code package (this is a Service Fabric concept and basically will result in restarting the offending service process).  

There are some interesting things here:  

- Note the use of ```AppName="xxx"``` in the goal. If that fact was not present (so, the app in Warning for example is not named "fabric:/PortEater42"), then Guan would move to the next rule in the file. This is a convenience syntax. That is, you could also create a variable (like ```MetricValue=?MetricValue```) that you could pull into the sub rule logic, as you can see (```?MetricValue >= 8500```) like this: 

```Prolog
Mitigate(AppName=?AppName, MetricName="EphemeralPorts", MetricValue=?MetricValue) :- ?AppName == "fabric:/PortEater42", ?MetricValue >= 8500,
	TimeScopedRestartCodePackage(4, 01:00:00).
```

However, that adds unnecessary noise or complexity to the sub rules; you already have a head full of facts, so you can just use a  more convenient (easier to read, less logic) way of expressing if this is the application we're looking for ```(AppName="fabric:/PortEater42")``` and that the ```MetricName``` is "EphemeralPorts".  So, testing for named arguments in the goal or head is a straightforward and easy to read (and write) approach for rule composition.

- Binding facts/data/values to a local variable for use in sub rule logic. ```MetricValue=?MetricValue```, for example. This syntax binds the value of the argument supplied to the Mitigate ```CompoundTerm``` object to a variable named ```?MetricValue```. This variable can then be used in the sub rules, as you can see. 

Sub rules here are really boolean paths. That is, each sub rule will evaluate to either be true or false (very basic logic!). If true, the next sub rule is evaluated until we reach an external or internal predicate (the auto-mitigation to execute, which is done by FabricHealer, not Guan). Thus the notion of path or workflow that leads to some mitigation or not (the rule either succeeds or fails at some point in the sub rule logic, including the final mitigation step in this case - if that fails, then the next rule will run).

- ```TimeScopedRestartCodePackage``` is an ```internal predicate```, which means it is defined only in the context of the rule file (there is no backing impl in C#, for example, as there must be for an external predicate (thus the notion of external versus internal). It is defined in the rule file like this: 

```Prolog
TimeScopedRestartCodePackage() :- RestartCodePackage(DoHealthChecks=true, MaxWaitTimeForHealthStateOk=00:10:00).
```

This will run an ```external predicate``` called ```RestartCodePackage``` (implemented in C#, just like Guan is) that will fire off a repair job (managed by FH and yet another service, RepairManager). The rule will succeed or fail based on the boolean result returned by the executor (FabricHealer) and surfaced to Guan (and thus the rule) by the external predicate. 

Spend some time looking at the details of ```RestartCodePackagePredicateType``` located in Repair\Guan folder. You will notice a very similar pattern in most of the external predicates, though some are not boolean in nature (so, they do not derive from or implement Guan's ```BooleanPredicateResolver``` type). In some cases, the external predicates return (or, more formally, bind) numeric values to a result that is then used in sub rules (these derive from Guan's ```GroundPredicateResolver```). An example of this type of external predicate is ```GetHealthEventHistoryPredicateType```. 

You should also read through the documentation on the FabricHealer repro: https://github.com/microsoft/service-fabric-healer/blob/main/Documentation/LogicWorkflows.md and not only focus on the implementation details until you are comfortable with the basic concepts. Have fun and learn!

**Comment by d-vyd** [comment]
Thank you for targeting my attention and presenting a walk-though of the code. I will study `RunGuanQueryAsync`. But, could I quickly run my use case by you to make sure I'm not heading toward a dead end or a mine field? I intend to use Guan to hold game state (reality) and characters' beliefs (about reality) in a text-based mobile app. In a previous desktop prototype, I used a planner ([fastdownward](https://www.fast-downward.org/))  for knowledge representation and action planning, constantly translating between simulation/game objects (C#) and [PDDL](https://en.wikipedia.org/wiki/Planning_Domain_Definition_Language). I'm hoping that Guan will let me (1) unify these parts more so I don't have to keep translating and (2) update state and beliefs in memory via `assert` and `retract` so I don't have to reload _all_ data _every_ turn for _each_ character. From my reading so far about Prolog, this seems feasible. I'm looking at Ivan Bratko's _PROLOG Programming for Artificial Intelligence_ and Brachman & Levesque's _Knowledge Representation and Reasoning_.

**Comment by d-vyd** [comment]
Charles, thank you for reminding me that Guan is not a complete Prolog implementation. I'll continue using CSharpProlog for the time being and check back here to read the getting started document.

**Comment by d-vyd** [comment]
I'm still lurking. Since I was last here, I learned that Mercury (another Prolog-like language) can compile to .NET assemblies and be included in C# projects. So, that is another option for me. May I ask, by "as soon as possible" for the Guan getting started document, do you mean within the next two weeks, two months? I see you also added the Retract statement as a work item. Is there a timeline for that?

**Comment by GitTorre** [comment]
Hopefully, the getting started doc will ship in the next week or sooner. It will be be based on the test project, with explanations of what is going on there, and some simple samples that are unrelated to FabricHealer or some larger consuming program.. For retract, there is no timeline yet. That will be done by Lu. I will touch base with him then let you know here about a timeline. Thanks for checking in.

**Comment by d-vyd** [comment]
Thanks for the update. Does Guan use the standard Prolog approach of Selective Linear Definite (SLD) clause resolution and depth first search with backtracking?

**Comment by GitTorre** [comment]
We use standard SLD resolution in Guan.

**Comment by GitTorre** [comment]
Getting Started document shipped. Also, a GuanExamples project that can be used to experiment with Guan inside a host application. The Getting Started document will likely evolve, but the assumption is that users of Guan already understand logic programming. The goal is get folks up to speed with how to use Guan in a containing .NET application. GuanExamples is a .NET Core 3.1 console application. The sample query expressions are very simplistic, by design. Since it is a sample app, the idea is that devs will experiment executing rules they write and learn how to execute queries. Feel free to add to the document if you want to showcase things you've learned that others will benefit from. Thanks in advance for experimenting with Guan and providing feedback. 

...Charles
